set DD_AGENT_OMNIBUS_BRANCH=win-test
set BUILD_USER_PASSWORD=DDBuildR0cks!
set DD_AGENT_BRANCH=epoch/5.23.0
set OMNIBUS_SOFTWARE_BRANCH=5.23.x
set INTEGRATIONS_CORE_BRANCH=epoch/5.23.0
set EPOCH_COLLECTORS_VERSION=1.2.1
set BUILD_TYPE=epoch-collectors
